// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerComm.proto

package net.communication;

public final class ServerComm {
  private ServerComm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface simpleExchangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:communication.simpleExchange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    net.communication.ServerComm.simpleExchange.simpleExchangeRequest getRequest();
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    net.communication.ServerComm.simpleExchange.simpleExchangeRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    net.communication.ServerComm.simpleExchange.simpleExchangeResponse getResponse();
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    net.communication.ServerComm.simpleExchange.simpleExchangeResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code communication.simpleExchange}
   */
  public static final class simpleExchange extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:communication.simpleExchange)
      simpleExchangeOrBuilder {
    // Use simpleExchange.newBuilder() to construct.
    private simpleExchange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private simpleExchange(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final simpleExchange defaultInstance;
    public static simpleExchange getDefaultInstance() {
      return defaultInstance;
    }

    public simpleExchange getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private simpleExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.communication.ServerComm.simpleExchange.simpleExchangeRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.communication.ServerComm.simpleExchange.simpleExchangeRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              net.communication.ServerComm.simpleExchange.simpleExchangeResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.communication.ServerComm.simpleExchange.simpleExchangeResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.communication.ServerComm.internal_static_communication_simpleExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.communication.ServerComm.internal_static_communication_simpleExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.communication.ServerComm.simpleExchange.class, net.communication.ServerComm.simpleExchange.Builder.class);
    }

    public static com.google.protobuf.Parser<simpleExchange> PARSER =
        new com.google.protobuf.AbstractParser<simpleExchange>() {
      public simpleExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new simpleExchange(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<simpleExchange> getParserForType() {
      return PARSER;
    }

    public interface simpleExchangeRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:communication.simpleExchange.simpleExchangeRequest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestHeader request_type = 1;</code>
       */
      boolean hasRequestType();
      /**
       * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestHeader request_type = 1;</code>
       */
      net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader getRequestType();

      /**
       * <code>optional string message = 2;</code>
       */
      boolean hasMessage();
      /**
       * <code>optional string message = 2;</code>
       */
      java.lang.String getMessage();
      /**
       * <code>optional string message = 2;</code>
       */
      com.google.protobuf.ByteString
          getMessageBytes();
    }
    /**
     * Protobuf type {@code communication.simpleExchange.simpleExchangeRequest}
     */
    public static final class simpleExchangeRequest extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:communication.simpleExchange.simpleExchangeRequest)
        simpleExchangeRequestOrBuilder {
      // Use simpleExchangeRequest.newBuilder() to construct.
      private simpleExchangeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private simpleExchangeRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final simpleExchangeRequest defaultInstance;
      public static simpleExchangeRequest getDefaultInstance() {
        return defaultInstance;
      }

      public simpleExchangeRequest getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private simpleExchangeRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader value = net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  requestType_ = value;
                }
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                message_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.communication.ServerComm.simpleExchange.simpleExchangeRequest.class, net.communication.ServerComm.simpleExchange.simpleExchangeRequest.Builder.class);
      }

      public static com.google.protobuf.Parser<simpleExchangeRequest> PARSER =
          new com.google.protobuf.AbstractParser<simpleExchangeRequest>() {
        public simpleExchangeRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new simpleExchangeRequest(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<simpleExchangeRequest> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code communication.simpleExchange.simpleExchangeRequest.RequestHeader}
       */
      public enum RequestHeader
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>CLUSTER_MEMBERSHIP = 1;</code>
         */
        CLUSTER_MEMBERSHIP(0, 1),
        /**
         * <code>PROBE = 2;</code>
         */
        PROBE(1, 2),
        /**
         * <code>SERVER_INFO = 3;</code>
         */
        SERVER_INFO(2, 3),
        /**
         * <code>SERVER_NAME = 4;</code>
         */
        SERVER_NAME(3, 4),
        ;

        /**
         * <code>CLUSTER_MEMBERSHIP = 1;</code>
         */
        public static final int CLUSTER_MEMBERSHIP_VALUE = 1;
        /**
         * <code>PROBE = 2;</code>
         */
        public static final int PROBE_VALUE = 2;
        /**
         * <code>SERVER_INFO = 3;</code>
         */
        public static final int SERVER_INFO_VALUE = 3;
        /**
         * <code>SERVER_NAME = 4;</code>
         */
        public static final int SERVER_NAME_VALUE = 4;


        public final int getNumber() { return value; }

        public static RequestHeader valueOf(int value) {
          switch (value) {
            case 1: return CLUSTER_MEMBERSHIP;
            case 2: return PROBE;
            case 3: return SERVER_INFO;
            case 4: return SERVER_NAME;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<RequestHeader>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<RequestHeader>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<RequestHeader>() {
                public RequestHeader findValueByNumber(int number) {
                  return RequestHeader.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return net.communication.ServerComm.simpleExchange.simpleExchangeRequest.getDescriptor().getEnumTypes().get(0);
        }

        private static final RequestHeader[] VALUES = values();

        public static RequestHeader valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private RequestHeader(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:communication.simpleExchange.simpleExchangeRequest.RequestHeader)
      }

      private int bitField0_;
      public static final int REQUEST_TYPE_FIELD_NUMBER = 1;
      private net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader requestType_;
      /**
       * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestHeader request_type = 1;</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestHeader request_type = 1;</code>
       */
      public net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader getRequestType() {
        return requestType_;
      }

      public static final int MESSAGE_FIELD_NUMBER = 2;
      private java.lang.Object message_;
      /**
       * <code>optional string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        requestType_ = net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader.CLUSTER_MEMBERSHIP;
        message_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasRequestType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, requestType_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getMessageBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, requestType_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getMessageBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.communication.ServerComm.simpleExchange.simpleExchangeRequest prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code communication.simpleExchange.simpleExchangeRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:communication.simpleExchange.simpleExchangeRequest)
          net.communication.ServerComm.simpleExchange.simpleExchangeRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.communication.ServerComm.simpleExchange.simpleExchangeRequest.class, net.communication.ServerComm.simpleExchange.simpleExchangeRequest.Builder.class);
        }

        // Construct using net.communication.ServerComm.simpleExchange.simpleExchangeRequest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          requestType_ = net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader.CLUSTER_MEMBERSHIP;
          bitField0_ = (bitField0_ & ~0x00000001);
          message_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor;
        }

        public net.communication.ServerComm.simpleExchange.simpleExchangeRequest getDefaultInstanceForType() {
          return net.communication.ServerComm.simpleExchange.simpleExchangeRequest.getDefaultInstance();
        }

        public net.communication.ServerComm.simpleExchange.simpleExchangeRequest build() {
          net.communication.ServerComm.simpleExchange.simpleExchangeRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.communication.ServerComm.simpleExchange.simpleExchangeRequest buildPartial() {
          net.communication.ServerComm.simpleExchange.simpleExchangeRequest result = new net.communication.ServerComm.simpleExchange.simpleExchangeRequest(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.requestType_ = requestType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.message_ = message_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.communication.ServerComm.simpleExchange.simpleExchangeRequest) {
            return mergeFrom((net.communication.ServerComm.simpleExchange.simpleExchangeRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.communication.ServerComm.simpleExchange.simpleExchangeRequest other) {
          if (other == net.communication.ServerComm.simpleExchange.simpleExchangeRequest.getDefaultInstance()) return this;
          if (other.hasRequestType()) {
            setRequestType(other.getRequestType());
          }
          if (other.hasMessage()) {
            bitField0_ |= 0x00000002;
            message_ = other.message_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasRequestType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.communication.ServerComm.simpleExchange.simpleExchangeRequest parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.communication.ServerComm.simpleExchange.simpleExchangeRequest) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader requestType_ = net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader.CLUSTER_MEMBERSHIP;
        /**
         * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestHeader request_type = 1;</code>
         */
        public boolean hasRequestType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestHeader request_type = 1;</code>
         */
        public net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader getRequestType() {
          return requestType_;
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestHeader request_type = 1;</code>
         */
        public Builder setRequestType(net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          requestType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestHeader request_type = 1;</code>
         */
        public Builder clearRequestType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          requestType_ = net.communication.ServerComm.simpleExchange.simpleExchangeRequest.RequestHeader.CLUSTER_MEMBERSHIP;
          onChanged();
          return this;
        }

        private java.lang.Object message_ = "";
        /**
         * <code>optional string message = 2;</code>
         */
        public boolean hasMessage() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public java.lang.String getMessage() {
          java.lang.Object ref = message_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              message_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMessageBytes() {
          java.lang.Object ref = message_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            message_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessage(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder clearMessage() {
          bitField0_ = (bitField0_ & ~0x00000002);
          message_ = getDefaultInstance().getMessage();
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessageBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:communication.simpleExchange.simpleExchangeRequest)
      }

      static {
        defaultInstance = new simpleExchangeRequest(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:communication.simpleExchange.simpleExchangeRequest)
    }

    public interface simpleExchangeResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:communication.simpleExchange.simpleExchangeResponse)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseHeader response_type = 1;</code>
       */
      boolean hasResponseType();
      /**
       * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseHeader response_type = 1;</code>
       */
      net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader getResponseType();

      /**
       * <code>optional string message = 2;</code>
       */
      boolean hasMessage();
      /**
       * <code>optional string message = 2;</code>
       */
      java.lang.String getMessage();
      /**
       * <code>optional string message = 2;</code>
       */
      com.google.protobuf.ByteString
          getMessageBytes();
    }
    /**
     * Protobuf type {@code communication.simpleExchange.simpleExchangeResponse}
     */
    public static final class simpleExchangeResponse extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:communication.simpleExchange.simpleExchangeResponse)
        simpleExchangeResponseOrBuilder {
      // Use simpleExchangeResponse.newBuilder() to construct.
      private simpleExchangeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private simpleExchangeResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final simpleExchangeResponse defaultInstance;
      public static simpleExchangeResponse getDefaultInstance() {
        return defaultInstance;
      }

      public simpleExchangeResponse getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private simpleExchangeResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader value = net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  responseType_ = value;
                }
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                message_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.communication.ServerComm.simpleExchange.simpleExchangeResponse.class, net.communication.ServerComm.simpleExchange.simpleExchangeResponse.Builder.class);
      }

      public static com.google.protobuf.Parser<simpleExchangeResponse> PARSER =
          new com.google.protobuf.AbstractParser<simpleExchangeResponse>() {
        public simpleExchangeResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new simpleExchangeResponse(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<simpleExchangeResponse> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code communication.simpleExchange.simpleExchangeResponse.ResponseHeader}
       */
      public enum ResponseHeader
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>CLUSTER_MEMBERSHIP_DENIED = 1;</code>
         */
        CLUSTER_MEMBERSHIP_DENIED(0, 1),
        /**
         * <code>CLUSTER_MEMBERSHIP_ACCEPTED = 2;</code>
         */
        CLUSTER_MEMBERSHIP_ACCEPTED(1, 2),
        /**
         * <code>PROBE = 3;</code>
         */
        PROBE(2, 3),
        /**
         * <code>SERVER_NAME = 4;</code>
         */
        SERVER_NAME(3, 4),
        /**
         * <code>SERVER_INFO = 5;</code>
         */
        SERVER_INFO(4, 5),
        ;

        /**
         * <code>CLUSTER_MEMBERSHIP_DENIED = 1;</code>
         */
        public static final int CLUSTER_MEMBERSHIP_DENIED_VALUE = 1;
        /**
         * <code>CLUSTER_MEMBERSHIP_ACCEPTED = 2;</code>
         */
        public static final int CLUSTER_MEMBERSHIP_ACCEPTED_VALUE = 2;
        /**
         * <code>PROBE = 3;</code>
         */
        public static final int PROBE_VALUE = 3;
        /**
         * <code>SERVER_NAME = 4;</code>
         */
        public static final int SERVER_NAME_VALUE = 4;
        /**
         * <code>SERVER_INFO = 5;</code>
         */
        public static final int SERVER_INFO_VALUE = 5;


        public final int getNumber() { return value; }

        public static ResponseHeader valueOf(int value) {
          switch (value) {
            case 1: return CLUSTER_MEMBERSHIP_DENIED;
            case 2: return CLUSTER_MEMBERSHIP_ACCEPTED;
            case 3: return PROBE;
            case 4: return SERVER_NAME;
            case 5: return SERVER_INFO;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ResponseHeader>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<ResponseHeader>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ResponseHeader>() {
                public ResponseHeader findValueByNumber(int number) {
                  return ResponseHeader.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return net.communication.ServerComm.simpleExchange.simpleExchangeResponse.getDescriptor().getEnumTypes().get(0);
        }

        private static final ResponseHeader[] VALUES = values();

        public static ResponseHeader valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private ResponseHeader(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:communication.simpleExchange.simpleExchangeResponse.ResponseHeader)
      }

      private int bitField0_;
      public static final int RESPONSE_TYPE_FIELD_NUMBER = 1;
      private net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader responseType_;
      /**
       * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseHeader response_type = 1;</code>
       */
      public boolean hasResponseType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseHeader response_type = 1;</code>
       */
      public net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader getResponseType() {
        return responseType_;
      }

      public static final int MESSAGE_FIELD_NUMBER = 2;
      private java.lang.Object message_;
      /**
       * <code>optional string message = 2;</code>
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        responseType_ = net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader.CLUSTER_MEMBERSHIP_DENIED;
        message_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasResponseType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, responseType_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getMessageBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, responseType_.getNumber());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getMessageBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.communication.ServerComm.simpleExchange.simpleExchangeResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(net.communication.ServerComm.simpleExchange.simpleExchangeResponse prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code communication.simpleExchange.simpleExchangeResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:communication.simpleExchange.simpleExchangeResponse)
          net.communication.ServerComm.simpleExchange.simpleExchangeResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.communication.ServerComm.simpleExchange.simpleExchangeResponse.class, net.communication.ServerComm.simpleExchange.simpleExchangeResponse.Builder.class);
        }

        // Construct using net.communication.ServerComm.simpleExchange.simpleExchangeResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          responseType_ = net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader.CLUSTER_MEMBERSHIP_DENIED;
          bitField0_ = (bitField0_ & ~0x00000001);
          message_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.communication.ServerComm.internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor;
        }

        public net.communication.ServerComm.simpleExchange.simpleExchangeResponse getDefaultInstanceForType() {
          return net.communication.ServerComm.simpleExchange.simpleExchangeResponse.getDefaultInstance();
        }

        public net.communication.ServerComm.simpleExchange.simpleExchangeResponse build() {
          net.communication.ServerComm.simpleExchange.simpleExchangeResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.communication.ServerComm.simpleExchange.simpleExchangeResponse buildPartial() {
          net.communication.ServerComm.simpleExchange.simpleExchangeResponse result = new net.communication.ServerComm.simpleExchange.simpleExchangeResponse(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.responseType_ = responseType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.message_ = message_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.communication.ServerComm.simpleExchange.simpleExchangeResponse) {
            return mergeFrom((net.communication.ServerComm.simpleExchange.simpleExchangeResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.communication.ServerComm.simpleExchange.simpleExchangeResponse other) {
          if (other == net.communication.ServerComm.simpleExchange.simpleExchangeResponse.getDefaultInstance()) return this;
          if (other.hasResponseType()) {
            setResponseType(other.getResponseType());
          }
          if (other.hasMessage()) {
            bitField0_ |= 0x00000002;
            message_ = other.message_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasResponseType()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.communication.ServerComm.simpleExchange.simpleExchangeResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.communication.ServerComm.simpleExchange.simpleExchangeResponse) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader responseType_ = net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader.CLUSTER_MEMBERSHIP_DENIED;
        /**
         * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseHeader response_type = 1;</code>
         */
        public boolean hasResponseType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseHeader response_type = 1;</code>
         */
        public net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader getResponseType() {
          return responseType_;
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseHeader response_type = 1;</code>
         */
        public Builder setResponseType(net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          responseType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseHeader response_type = 1;</code>
         */
        public Builder clearResponseType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          responseType_ = net.communication.ServerComm.simpleExchange.simpleExchangeResponse.ResponseHeader.CLUSTER_MEMBERSHIP_DENIED;
          onChanged();
          return this;
        }

        private java.lang.Object message_ = "";
        /**
         * <code>optional string message = 2;</code>
         */
        public boolean hasMessage() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public java.lang.String getMessage() {
          java.lang.Object ref = message_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              message_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public com.google.protobuf.ByteString
            getMessageBytes() {
          java.lang.Object ref = message_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            message_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessage(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder clearMessage() {
          bitField0_ = (bitField0_ & ~0x00000002);
          message_ = getDefaultInstance().getMessage();
          onChanged();
          return this;
        }
        /**
         * <code>optional string message = 2;</code>
         */
        public Builder setMessageBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          message_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:communication.simpleExchange.simpleExchangeResponse)
      }

      static {
        defaultInstance = new simpleExchangeResponse(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:communication.simpleExchange.simpleExchangeResponse)
    }

    private int bitField0_;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.communication.ServerComm.simpleExchange.simpleExchangeRequest request_;
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    public net.communication.ServerComm.simpleExchange.simpleExchangeRequest getRequest() {
      return request_;
    }
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    public net.communication.ServerComm.simpleExchange.simpleExchangeRequestOrBuilder getRequestOrBuilder() {
      return request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private net.communication.ServerComm.simpleExchange.simpleExchangeResponse response_;
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    public net.communication.ServerComm.simpleExchange.simpleExchangeResponse getResponse() {
      return response_;
    }
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    public net.communication.ServerComm.simpleExchange.simpleExchangeResponseOrBuilder getResponseOrBuilder() {
      return response_;
    }

    private void initFields() {
      request_ = net.communication.ServerComm.simpleExchange.simpleExchangeRequest.getDefaultInstance();
      response_ = net.communication.ServerComm.simpleExchange.simpleExchangeResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, response_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, response_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static net.communication.ServerComm.simpleExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.communication.ServerComm.simpleExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.communication.ServerComm.simpleExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.communication.ServerComm.simpleExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.communication.ServerComm.simpleExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.communication.ServerComm.simpleExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.communication.ServerComm.simpleExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.communication.ServerComm.simpleExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.communication.ServerComm.simpleExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.communication.ServerComm.simpleExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(net.communication.ServerComm.simpleExchange prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code communication.simpleExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:communication.simpleExchange)
        net.communication.ServerComm.simpleExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.communication.ServerComm.internal_static_communication_simpleExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.communication.ServerComm.internal_static_communication_simpleExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.communication.ServerComm.simpleExchange.class, net.communication.ServerComm.simpleExchange.Builder.class);
      }

      // Construct using net.communication.ServerComm.simpleExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getResponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = net.communication.ServerComm.simpleExchange.simpleExchangeRequest.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (responseBuilder_ == null) {
          response_ = net.communication.ServerComm.simpleExchange.simpleExchangeResponse.getDefaultInstance();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.communication.ServerComm.internal_static_communication_simpleExchange_descriptor;
      }

      public net.communication.ServerComm.simpleExchange getDefaultInstanceForType() {
        return net.communication.ServerComm.simpleExchange.getDefaultInstance();
      }

      public net.communication.ServerComm.simpleExchange build() {
        net.communication.ServerComm.simpleExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.communication.ServerComm.simpleExchange buildPartial() {
        net.communication.ServerComm.simpleExchange result = new net.communication.ServerComm.simpleExchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.communication.ServerComm.simpleExchange) {
          return mergeFrom((net.communication.ServerComm.simpleExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.communication.ServerComm.simpleExchange other) {
        if (other == net.communication.ServerComm.simpleExchange.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.communication.ServerComm.simpleExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.communication.ServerComm.simpleExchange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private net.communication.ServerComm.simpleExchange.simpleExchangeRequest request_ = net.communication.ServerComm.simpleExchange.simpleExchangeRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          net.communication.ServerComm.simpleExchange.simpleExchangeRequest, net.communication.ServerComm.simpleExchange.simpleExchangeRequest.Builder, net.communication.ServerComm.simpleExchange.simpleExchangeRequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public net.communication.ServerComm.simpleExchange.simpleExchangeRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public Builder setRequest(net.communication.ServerComm.simpleExchange.simpleExchangeRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public Builder setRequest(
          net.communication.ServerComm.simpleExchange.simpleExchangeRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public Builder mergeRequest(net.communication.ServerComm.simpleExchange.simpleExchangeRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              request_ != net.communication.ServerComm.simpleExchange.simpleExchangeRequest.getDefaultInstance()) {
            request_ =
              net.communication.ServerComm.simpleExchange.simpleExchangeRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = net.communication.ServerComm.simpleExchange.simpleExchangeRequest.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public net.communication.ServerComm.simpleExchange.simpleExchangeRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public net.communication.ServerComm.simpleExchange.simpleExchangeRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          net.communication.ServerComm.simpleExchange.simpleExchangeRequest, net.communication.ServerComm.simpleExchange.simpleExchangeRequest.Builder, net.communication.ServerComm.simpleExchange.simpleExchangeRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.communication.ServerComm.simpleExchange.simpleExchangeRequest, net.communication.ServerComm.simpleExchange.simpleExchangeRequest.Builder, net.communication.ServerComm.simpleExchange.simpleExchangeRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private net.communication.ServerComm.simpleExchange.simpleExchangeResponse response_ = net.communication.ServerComm.simpleExchange.simpleExchangeResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          net.communication.ServerComm.simpleExchange.simpleExchangeResponse, net.communication.ServerComm.simpleExchange.simpleExchangeResponse.Builder, net.communication.ServerComm.simpleExchange.simpleExchangeResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public net.communication.ServerComm.simpleExchange.simpleExchangeResponse getResponse() {
        if (responseBuilder_ == null) {
          return response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public Builder setResponse(net.communication.ServerComm.simpleExchange.simpleExchangeResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public Builder setResponse(
          net.communication.ServerComm.simpleExchange.simpleExchangeResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public Builder mergeResponse(net.communication.ServerComm.simpleExchange.simpleExchangeResponse value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              response_ != net.communication.ServerComm.simpleExchange.simpleExchangeResponse.getDefaultInstance()) {
            response_ =
              net.communication.ServerComm.simpleExchange.simpleExchangeResponse.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = net.communication.ServerComm.simpleExchange.simpleExchangeResponse.getDefaultInstance();
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public net.communication.ServerComm.simpleExchange.simpleExchangeResponse.Builder getResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public net.communication.ServerComm.simpleExchange.simpleExchangeResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_;
        }
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          net.communication.ServerComm.simpleExchange.simpleExchangeResponse, net.communication.ServerComm.simpleExchange.simpleExchangeResponse.Builder, net.communication.ServerComm.simpleExchange.simpleExchangeResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.communication.ServerComm.simpleExchange.simpleExchangeResponse, net.communication.ServerComm.simpleExchange.simpleExchangeResponse.Builder, net.communication.ServerComm.simpleExchange.simpleExchangeResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:communication.simpleExchange)
    }

    static {
      defaultInstance = new simpleExchange(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:communication.simpleExchange)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_communication_simpleExchange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_communication_simpleExchange_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_communication_simpleExchange_simpleExchangeRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_communication_simpleExchange_simpleExchangeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ServerComm.proto\022\rcommunication\"\377\004\n\016si" +
      "mpleExchange\022D\n\007request\030\001 \001(\01323.communic" +
      "ation.simpleExchange.simpleExchangeReque" +
      "st\022F\n\010response\030\002 \001(\01324.communication.sim" +
      "pleExchange.simpleExchangeResponse\032\327\001\n\025s" +
      "impleExchangeRequest\022W\n\014request_type\030\001 \002" +
      "(\0162A.communication.simpleExchange.simple" +
      "ExchangeRequest.RequestHeader\022\017\n\007message" +
      "\030\002 \001(\t\"T\n\rRequestHeader\022\026\n\022CLUSTER_MEMBE" +
      "RSHIP\020\001\022\t\n\005PROBE\020\002\022\017\n\013SERVER_INFO\020\003\022\017\n\013S",
      "ERVER_NAME\020\004\032\204\002\n\026simpleExchangeResponse\022" +
      "Z\n\rresponse_type\030\001 \002(\0162C.communication.s" +
      "impleExchange.simpleExchangeResponse.Res" +
      "ponseHeader\022\017\n\007message\030\002 \001(\t\"}\n\016Response" +
      "Header\022\035\n\031CLUSTER_MEMBERSHIP_DENIED\020\001\022\037\n" +
      "\033CLUSTER_MEMBERSHIP_ACCEPTED\020\002\022\t\n\005PROBE\020" +
      "\003\022\017\n\013SERVER_NAME\020\004\022\017\n\013SERVER_INFO\020\005B\023\n\021n" +
      "et.communication"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_communication_simpleExchange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_communication_simpleExchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_communication_simpleExchange_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor =
      internal_static_communication_simpleExchange_descriptor.getNestedTypes().get(0);
    internal_static_communication_simpleExchange_simpleExchangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor,
        new java.lang.String[] { "RequestType", "Message", });
    internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor =
      internal_static_communication_simpleExchange_descriptor.getNestedTypes().get(1);
    internal_static_communication_simpleExchange_simpleExchangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor,
        new java.lang.String[] { "ResponseType", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
