// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerComm.proto

package net.communication;

public final class SimpleExchangeComm {
  private SimpleExchangeComm() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface simpleExchangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:communication.simpleExchange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest getRequest();
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse getResponse();
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponseOrBuilder getResponseOrBuilder();

    /**
     * <code>optional int32 id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 3;</code>
     */
    int getId();

    /**
     * <code>optional int32 time_stamp = 4;</code>
     */
    boolean hasTimeStamp();
    /**
     * <code>optional int32 time_stamp = 4;</code>
     */
    int getTimeStamp();

    /**
     * <code>optional int32 packet_number = 5;</code>
     */
    boolean hasPacketNumber();
    /**
     * <code>optional int32 packet_number = 5;</code>
     */
    int getPacketNumber();
  }
  /**
   * Protobuf type {@code communication.simpleExchange}
   */
  public  static final class simpleExchange extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:communication.simpleExchange)
      simpleExchangeOrBuilder {
    // Use simpleExchange.newBuilder() to construct.
    private simpleExchange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private simpleExchange() {
      id_ = 0;
      timeStamp_ = 0;
      packetNumber_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private simpleExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      @SuppressWarnings("unused")
	int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              id_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              timeStamp_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              packetNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.communication.SimpleExchangeComm.simpleExchange.class, net.communication.SimpleExchangeComm.simpleExchange.Builder.class);
    }

    public interface simpleExchangeRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:communication.simpleExchange.simpleExchangeRequest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestType request_type = 1;</code>
       */
      boolean hasRequestType();
      /**
       * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestType request_type = 1;</code>
       */
      net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType getRequestType();

      /**
       * <code>optional string request_note = 2;</code>
       */
      boolean hasRequestNote();
      /**
       * <code>optional string request_note = 2;</code>
       */
      java.lang.String getRequestNote();
      /**
       * <code>optional string request_note = 2;</code>
       */
      com.google.protobuf.ByteString
          getRequestNoteBytes();
    }
    /**
     * Protobuf type {@code communication.simpleExchange.simpleExchangeRequest}
     */
    public  static final class simpleExchangeRequest extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:communication.simpleExchange.simpleExchangeRequest)
        simpleExchangeRequestOrBuilder {
      // Use simpleExchangeRequest.newBuilder() to construct.
      private simpleExchangeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private simpleExchangeRequest() {
        requestType_ = 0;
        requestNote_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private simpleExchangeRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        @SuppressWarnings("unused")
		int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType value = net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  requestType_ = rawValue;
                }
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                requestNote_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.class, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.Builder.class);
      }

      /**
       * Protobuf enum {@code communication.simpleExchange.simpleExchangeRequest.RequestType}
       */
      public enum RequestType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>PROBE = 0;</code>
         */
        PROBE(0, 0),
        /**
         * <code>CLUSTER_MEMBERSHIP_REQUEST = 1;</code>
         */
        CLUSTER_MEMBERSHIP_REQUEST(1, 1),
        /**
         * <code>SERVER_NAME = 2;</code>
         */
        SERVER_NAME(2, 2),
        /**
         * <code>SERVER_INFO = 3;</code>
         */
        SERVER_INFO(3, 3),
        ;

        /**
         * <code>PROBE = 0;</code>
         */
        public static final int PROBE_VALUE = 0;
        /**
         * <code>CLUSTER_MEMBERSHIP_REQUEST = 1;</code>
         */
        public static final int CLUSTER_MEMBERSHIP_REQUEST_VALUE = 1;
        /**
         * <code>SERVER_NAME = 2;</code>
         */
        public static final int SERVER_NAME_VALUE = 2;
        /**
         * <code>SERVER_INFO = 3;</code>
         */
        public static final int SERVER_INFO_VALUE = 3;


        public final int getNumber() {
          return value;
        }

        public static RequestType valueOf(int value) {
          switch (value) {
            case 0: return PROBE;
            case 1: return CLUSTER_MEMBERSHIP_REQUEST;
            case 2: return SERVER_NAME;
            case 3: return SERVER_INFO;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            RequestType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
                public RequestType findValueByNumber(int number) {
                  return RequestType.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.getDescriptor().getEnumTypes().get(0);
        }

        private static final RequestType[] VALUES = values();

        public static RequestType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private RequestType(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:communication.simpleExchange.simpleExchangeRequest.RequestType)
      }

      private int bitField0_;
      public static final int REQUEST_TYPE_FIELD_NUMBER = 1;
      private int requestType_;
      /**
       * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestType request_type = 1;</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestType request_type = 1;</code>
       */
      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType getRequestType() {
        net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType result = net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType.valueOf(requestType_);
        return result == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType.PROBE : result;
      }

      public static final int REQUEST_NOTE_FIELD_NUMBER = 2;
      private volatile java.lang.Object requestNote_;
      /**
       * <code>optional string request_note = 2;</code>
       */
      public boolean hasRequestNote() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string request_note = 2;</code>
       */
      public java.lang.String getRequestNote() {
        java.lang.Object ref = requestNote_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestNote_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string request_note = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRequestNoteBytes() {
        java.lang.Object ref = requestNote_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestNote_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasRequestType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, requestType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 2, requestNote_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, requestType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(2, requestNote_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code communication.simpleExchange.simpleExchangeRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:communication.simpleExchange.simpleExchangeRequest)
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.class, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.Builder.class);
        }

        // Construct using net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          requestType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          requestNote_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor;
        }

        public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest getDefaultInstanceForType() {
          return net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.getDefaultInstance();
        }

        public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest build() {
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest buildPartial() {
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest result = new net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.requestType_ = requestType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.requestNote_ = requestNote_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest) {
            return mergeFrom((net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest other) {
          if (other == net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.getDefaultInstance()) return this;
          if (other.hasRequestType()) {
            setRequestType(other.getRequestType());
          }
          if (other.hasRequestNote()) {
            bitField0_ |= 0x00000002;
            requestNote_ = other.requestNote_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasRequestType()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int requestType_ = 0;
        /**
         * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestType request_type = 1;</code>
         */
        public boolean hasRequestType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestType request_type = 1;</code>
         */
        public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType getRequestType() {
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType result = net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType.valueOf(requestType_);
          return result == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType.PROBE : result;
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestType request_type = 1;</code>
         */
        public Builder setRequestType(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.RequestType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          requestType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeRequest.RequestType request_type = 1;</code>
         */
        public Builder clearRequestType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          requestType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object requestNote_ = "";
        /**
         * <code>optional string request_note = 2;</code>
         */
        public boolean hasRequestNote() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public java.lang.String getRequestNote() {
          java.lang.Object ref = requestNote_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              requestNote_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public com.google.protobuf.ByteString
            getRequestNoteBytes() {
          java.lang.Object ref = requestNote_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            requestNote_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public Builder setRequestNote(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          requestNote_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public Builder clearRequestNote() {
          bitField0_ = (bitField0_ & ~0x00000002);
          requestNote_ = getDefaultInstance().getRequestNote();
          onChanged();
          return this;
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public Builder setRequestNoteBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          requestNote_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:communication.simpleExchange.simpleExchangeRequest)
      }

      // @@protoc_insertion_point(class_scope:communication.simpleExchange.simpleExchangeRequest)
      private static final net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest();
      }

      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<simpleExchangeRequest>
          PARSER = new com.google.protobuf.AbstractParser<simpleExchangeRequest>() {
        public simpleExchangeRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new simpleExchangeRequest(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<simpleExchangeRequest> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<simpleExchangeRequest> getParserForType() {
        return PARSER;
      }

      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface simpleExchangeResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:communication.simpleExchange.simpleExchangeResponse)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseType response_type = 1;</code>
       */
      boolean hasResponseType();
      /**
       * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseType response_type = 1;</code>
       */
      net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType getResponseType();

      /**
       * <code>optional string response_note = 2;</code>
       */
      boolean hasResponseNote();
      /**
       * <code>optional string response_note = 2;</code>
       */
      java.lang.String getResponseNote();
      /**
       * <code>optional string response_note = 2;</code>
       */
      com.google.protobuf.ByteString
          getResponseNoteBytes();
    }
    /**
     * Protobuf type {@code communication.simpleExchange.simpleExchangeResponse}
     */
    public  static final class simpleExchangeResponse extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:communication.simpleExchange.simpleExchangeResponse)
        simpleExchangeResponseOrBuilder {
      // Use simpleExchangeResponse.newBuilder() to construct.
      private simpleExchangeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private simpleExchangeResponse() {
        responseType_ = 0;
        responseNote_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private simpleExchangeResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        @SuppressWarnings("unused")
		int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType value = net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  responseType_ = rawValue;
                }
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                responseNote_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.class, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.Builder.class);
      }

      /**
       * Protobuf enum {@code communication.simpleExchange.simpleExchangeResponse.ResponseType}
       */
      public enum ResponseType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>PROBE = 0;</code>
         */
        PROBE(0, 0),
        /**
         * <code>CLUSTER_MEMBERSHIP_ACCEPT = 1;</code>
         */
        CLUSTER_MEMBERSHIP_ACCEPT(1, 1),
        /**
         * <code>CLUSTER_MEMBERSHIP_DENIED = 2;</code>
         */
        CLUSTER_MEMBERSHIP_DENIED(2, 2),
        /**
         * <code>SERVER_NAME = 3;</code>
         */
        SERVER_NAME(3, 3),
        /**
         * <code>SERVER_INFO = 4;</code>
         */
        SERVER_INFO(4, 4),
        ;

        /**
         * <code>PROBE = 0;</code>
         */
        public static final int PROBE_VALUE = 0;
        /**
         * <code>CLUSTER_MEMBERSHIP_ACCEPT = 1;</code>
         */
        public static final int CLUSTER_MEMBERSHIP_ACCEPT_VALUE = 1;
        /**
         * <code>CLUSTER_MEMBERSHIP_DENIED = 2;</code>
         */
        public static final int CLUSTER_MEMBERSHIP_DENIED_VALUE = 2;
        /**
         * <code>SERVER_NAME = 3;</code>
         */
        public static final int SERVER_NAME_VALUE = 3;
        /**
         * <code>SERVER_INFO = 4;</code>
         */
        public static final int SERVER_INFO_VALUE = 4;


        public final int getNumber() {
          return value;
        }

        public static ResponseType valueOf(int value) {
          switch (value) {
            case 0: return PROBE;
            case 1: return CLUSTER_MEMBERSHIP_ACCEPT;
            case 2: return CLUSTER_MEMBERSHIP_DENIED;
            case 3: return SERVER_NAME;
            case 4: return SERVER_INFO;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            ResponseType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
                public ResponseType findValueByNumber(int number) {
                  return ResponseType.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.getDescriptor().getEnumTypes().get(0);
        }

        private static final ResponseType[] VALUES = values();

        public static ResponseType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private ResponseType(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:communication.simpleExchange.simpleExchangeResponse.ResponseType)
      }

      private int bitField0_;
      public static final int RESPONSE_TYPE_FIELD_NUMBER = 1;
      private int responseType_;
      /**
       * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseType response_type = 1;</code>
       */
      public boolean hasResponseType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseType response_type = 1;</code>
       */
      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType getResponseType() {
        net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType result = net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType.valueOf(responseType_);
        return result == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType.PROBE : result;
      }

      public static final int RESPONSE_NOTE_FIELD_NUMBER = 2;
      private volatile java.lang.Object responseNote_;
      /**
       * <code>optional string response_note = 2;</code>
       */
      public boolean hasResponseNote() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string response_note = 2;</code>
       */
      public java.lang.String getResponseNote() {
        java.lang.Object ref = responseNote_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            responseNote_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string response_note = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseNoteBytes() {
        java.lang.Object ref = responseNote_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseNote_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasResponseType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, responseType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 2, responseNote_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, responseType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(2, responseNote_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code communication.simpleExchange.simpleExchangeResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:communication.simpleExchange.simpleExchangeResponse)
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.class, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.Builder.class);
        }

        // Construct using net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          responseType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          responseNote_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor;
        }

        public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse getDefaultInstanceForType() {
          return net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.getDefaultInstance();
        }

        public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse build() {
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse buildPartial() {
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse result = new net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.responseType_ = responseType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.responseNote_ = responseNote_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse) {
            return mergeFrom((net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse other) {
          if (other == net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.getDefaultInstance()) return this;
          if (other.hasResponseType()) {
            setResponseType(other.getResponseType());
          }
          if (other.hasResponseNote()) {
            bitField0_ |= 0x00000002;
            responseNote_ = other.responseNote_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasResponseType()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int responseType_ = 0;
        /**
         * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseType response_type = 1;</code>
         */
        public boolean hasResponseType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseType response_type = 1;</code>
         */
        public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType getResponseType() {
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType result = net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType.valueOf(responseType_);
          return result == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType.PROBE : result;
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseType response_type = 1;</code>
         */
        public Builder setResponseType(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.ResponseType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          responseType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required .communication.simpleExchange.simpleExchangeResponse.ResponseType response_type = 1;</code>
         */
        public Builder clearResponseType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          responseType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object responseNote_ = "";
        /**
         * <code>optional string response_note = 2;</code>
         */
        public boolean hasResponseNote() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public java.lang.String getResponseNote() {
          java.lang.Object ref = responseNote_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              responseNote_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public com.google.protobuf.ByteString
            getResponseNoteBytes() {
          java.lang.Object ref = responseNote_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            responseNote_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public Builder setResponseNote(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          responseNote_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public Builder clearResponseNote() {
          bitField0_ = (bitField0_ & ~0x00000002);
          responseNote_ = getDefaultInstance().getResponseNote();
          onChanged();
          return this;
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public Builder setResponseNoteBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          responseNote_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:communication.simpleExchange.simpleExchangeResponse)
      }

      // @@protoc_insertion_point(class_scope:communication.simpleExchange.simpleExchangeResponse)
      private static final net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse();
      }

      public static net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<simpleExchangeResponse>
          PARSER = new com.google.protobuf.AbstractParser<simpleExchangeResponse>() {
        public simpleExchangeResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new simpleExchangeResponse(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<simpleExchangeResponse> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<simpleExchangeResponse> getParserForType() {
        return PARSER;
      }

      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest request_;
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest getRequest() {
      return request_ == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
     */
    public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequestOrBuilder getRequestOrBuilder() {
      return request_ == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.getDefaultInstance() : request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse response_;
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse getResponse() {
      return response_ == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
     */
    public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponseOrBuilder getResponseOrBuilder() {
      return response_ == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.getDefaultInstance() : response_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int id_;
    /**
     * <code>optional int32 id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 id = 3;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TIME_STAMP_FIELD_NUMBER = 4;
    private int timeStamp_;
    /**
     * <code>optional int32 time_stamp = 4;</code>
     */
    public boolean hasTimeStamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 time_stamp = 4;</code>
     */
    public int getTimeStamp() {
      return timeStamp_;
    }

    public static final int PACKET_NUMBER_FIELD_NUMBER = 5;
    private int packetNumber_;
    /**
     * <code>optional int32 packet_number = 5;</code>
     */
    public boolean hasPacketNumber() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 packet_number = 5;</code>
     */
    public int getPacketNumber() {
      return packetNumber_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getResponse());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, timeStamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, packetNumber_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponse());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, id_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, timeStamp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, packetNumber_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static net.communication.SimpleExchangeComm.simpleExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.communication.SimpleExchangeComm.simpleExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.communication.SimpleExchangeComm.simpleExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.communication.SimpleExchangeComm.simpleExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.communication.SimpleExchangeComm.simpleExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.communication.SimpleExchangeComm.simpleExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.communication.SimpleExchangeComm.simpleExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.communication.SimpleExchangeComm.simpleExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.communication.SimpleExchangeComm.simpleExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.communication.SimpleExchangeComm.simpleExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.communication.SimpleExchangeComm.simpleExchange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code communication.simpleExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:communication.simpleExchange)
        net.communication.SimpleExchangeComm.simpleExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.communication.SimpleExchangeComm.simpleExchange.class, net.communication.SimpleExchangeComm.simpleExchange.Builder.class);
      }

      // Construct using net.communication.SimpleExchangeComm.simpleExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getResponseFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        timeStamp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        packetNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.communication.SimpleExchangeComm.internal_static_communication_simpleExchange_descriptor;
      }

      public net.communication.SimpleExchangeComm.simpleExchange getDefaultInstanceForType() {
        return net.communication.SimpleExchangeComm.simpleExchange.getDefaultInstance();
      }

      public net.communication.SimpleExchangeComm.simpleExchange build() {
        net.communication.SimpleExchangeComm.simpleExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.communication.SimpleExchangeComm.simpleExchange buildPartial() {
        net.communication.SimpleExchangeComm.simpleExchange result = new net.communication.SimpleExchangeComm.simpleExchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.timeStamp_ = timeStamp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.packetNumber_ = packetNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.communication.SimpleExchangeComm.simpleExchange) {
          return mergeFrom((net.communication.SimpleExchangeComm.simpleExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.communication.SimpleExchangeComm.simpleExchange other) {
        if (other == net.communication.SimpleExchangeComm.simpleExchange.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTimeStamp()) {
          setTimeStamp(other.getTimeStamp());
        }
        if (other.hasPacketNumber()) {
          setPacketNumber(other.getPacketNumber());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.communication.SimpleExchangeComm.simpleExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.communication.SimpleExchangeComm.simpleExchange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest request_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.Builder, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public Builder setRequest(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public Builder setRequest(
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public Builder mergeRequest(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              request_ != null &&
              request_ != net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.getDefaultInstance()) {
            request_ =
              net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeRequest request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.Builder, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequest.Builder, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse response_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.Builder, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public Builder setResponse(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public Builder setResponse(
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public Builder mergeResponse(net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              response_ != null &&
              response_ != net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.getDefaultInstance()) {
            response_ =
              net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.Builder getResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      public net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .communication.simpleExchange.simpleExchangeResponse response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.Builder, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponse.Builder, net.communication.SimpleExchangeComm.simpleExchange.simpleExchangeResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      private int id_ ;
      /**
       * <code>optional int32 id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 id = 3;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 3;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = 0;
        onChanged();
        return this;
      }

      private int timeStamp_ ;
      /**
       * <code>optional int32 time_stamp = 4;</code>
       */
      public boolean hasTimeStamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 time_stamp = 4;</code>
       */
      public int getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>optional int32 time_stamp = 4;</code>
       */
      public Builder setTimeStamp(int value) {
        bitField0_ |= 0x00000008;
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 time_stamp = 4;</code>
       */
      public Builder clearTimeStamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        timeStamp_ = 0;
        onChanged();
        return this;
      }

      private int packetNumber_ ;
      /**
       * <code>optional int32 packet_number = 5;</code>
       */
      public boolean hasPacketNumber() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 packet_number = 5;</code>
       */
      public int getPacketNumber() {
        return packetNumber_;
      }
      /**
       * <code>optional int32 packet_number = 5;</code>
       */
      public Builder setPacketNumber(int value) {
        bitField0_ |= 0x00000010;
        packetNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 packet_number = 5;</code>
       */
      public Builder clearPacketNumber() {
        bitField0_ = (bitField0_ & ~0x00000010);
        packetNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:communication.simpleExchange)
    }

    // @@protoc_insertion_point(class_scope:communication.simpleExchange)
    private static final net.communication.SimpleExchangeComm.simpleExchange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.communication.SimpleExchangeComm.simpleExchange();
    }

    public static net.communication.SimpleExchangeComm.simpleExchange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<simpleExchange>
        PARSER = new com.google.protobuf.AbstractParser<simpleExchange>() {
      public simpleExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new simpleExchange(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<simpleExchange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<simpleExchange> getParserForType() {
      return PARSER;
    }

    public net.communication.SimpleExchangeComm.simpleExchange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_communication_simpleExchange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_communication_simpleExchange_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_communication_simpleExchange_simpleExchangeRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_communication_simpleExchange_simpleExchangeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020ServerComm.proto\022\rcommunication\"\277\005\n\016si" +
      "mpleExchange\022D\n\007request\030\001 \001(\01323.communic" +
      "ation.simpleExchange.simpleExchangeReque" +
      "st\022F\n\010response\030\002 \001(\01324.communication.sim" +
      "pleExchange.simpleExchangeResponse\022\n\n\002id" +
      "\030\003 \001(\005\022\022\n\ntime_stamp\030\004 \001(\005\022\025\n\rpacket_num" +
      "ber\030\005 \001(\005\032\340\001\n\025simpleExchangeRequest\022U\n\014r" +
      "equest_type\030\001 \002(\0162?.communication.simple" +
      "Exchange.simpleExchangeRequest.RequestTy" +
      "pe\022\024\n\014request_note\030\002 \001(\t\"Z\n\013RequestType\022",
      "\t\n\005PROBE\020\000\022\036\n\032CLUSTER_MEMBERSHIP_REQUEST" +
      "\020\001\022\017\n\013SERVER_NAME\020\002\022\017\n\013SERVER_INFO\020\003\032\204\002\n" +
      "\026simpleExchangeResponse\022X\n\rresponse_type" +
      "\030\001 \002(\0162A.communication.simpleExchange.si" +
      "mpleExchangeResponse.ResponseType\022\025\n\rres" +
      "ponse_note\030\002 \001(\t\"y\n\014ResponseType\022\t\n\005PROB" +
      "E\020\000\022\035\n\031CLUSTER_MEMBERSHIP_ACCEPT\020\001\022\035\n\031CL" +
      "USTER_MEMBERSHIP_DENIED\020\002\022\017\n\013SERVER_NAME" +
      "\020\003\022\017\n\013SERVER_INFO\020\004B\'\n\021net.communication" +
      "B\022SimpleExchangeComm"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_communication_simpleExchange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_communication_simpleExchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_communication_simpleExchange_descriptor,
        new java.lang.String[] { "Request", "Response", "Id", "TimeStamp", "PacketNumber", });
    internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor =
      internal_static_communication_simpleExchange_descriptor.getNestedTypes().get(0);
    internal_static_communication_simpleExchange_simpleExchangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_communication_simpleExchange_simpleExchangeRequest_descriptor,
        new java.lang.String[] { "RequestType", "RequestNote", });
    internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor =
      internal_static_communication_simpleExchange_descriptor.getNestedTypes().get(1);
    internal_static_communication_simpleExchange_simpleExchangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_communication_simpleExchange_simpleExchangeResponse_descriptor,
        new java.lang.String[] { "ResponseType", "ResponseNote", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
