/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panel;

import multiplayergamelauncher.AppState;
import multiplayergamelauncher.ProgressListener;
import profile.User;

/**
 *
 * @author amind_000
 */
public class HomePanel extends javax.swing.JPanel {
	private ProgressListener listener;
	private User loggedInUser;
    /**
     * Creates new form HomePanel
     * @param loggedInUser 
     */
    public HomePanel(ProgressListener listener, User loggedInUser) {
        this.listener=listener;
        this.loggedInUser=loggedInUser;
        initComponents();
    }
    public void onEnter(){
        WelcomeTag.setText(loggedInUser.getName());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JoinGameButton = new javax.swing.JButton();
        CreateGameButton = new javax.swing.JButton();
        DirectConnectButton = new javax.swing.JButton();
        EditProfileButton = new javax.swing.JButton();
        WelcomeTag = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("BankGothic Md BT", 1, 48)); // NOI18N
        jLabel1.setText("Multiplayer");

        JoinGameButton.setText("Join Game");
        JoinGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JoinGameButtonActionPerformed(evt);
            }
        });

        CreateGameButton.setText("Create Game");
        CreateGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateGameButtonActionPerformed(evt);
            }
        });

        DirectConnectButton.setText("Direct Connect");
        DirectConnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DirectConnectButtonActionPerformed(evt);
            }
        });

        EditProfileButton.setText("Edit Profile");
        EditProfileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditProfileButtonActionPerformed(evt);
            }
        });
        WelcomeTag.setText(loggedInUser.getName());
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(JoinGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CreateGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(EditProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DirectConnectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(WelcomeTag)))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(WelcomeTag)
                .addGap(18, 18, 18)
                .addComponent(JoinGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CreateGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DirectConnectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditProfileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DirectConnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DirectConnectButtonActionPerformed
        listener.progressTo(AppState.DIRECT_CONNECT);
    }//GEN-LAST:event_DirectConnectButtonActionPerformed

    private void CreateGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateGameButtonActionPerformed
    	listener.progressTo(AppState.CREATE_SERVER);
    }//GEN-LAST:event_CreateGameButtonActionPerformed

    private void EditProfileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProfileButtonActionPerformed
        listener.progressTo(AppState.EDIT_PROFILE);
    }//GEN-LAST:event_EditProfileButtonActionPerformed

    private void JoinGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JoinGameButtonActionPerformed
        listener.progressTo(AppState.SERVER_SELECT);
    }//GEN-LAST:event_JoinGameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateGameButton;
    private javax.swing.JButton DirectConnectButton;
    private javax.swing.JButton EditProfileButton;
    private javax.swing.JButton JoinGameButton;
    private javax.swing.JLabel WelcomeTag;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
