/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panel;

import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import hooks.GameHooks;
import multiplayergamelauncher.AppState;
import multiplayergamelauncher.ApplicationManager;
import net.Config;
import net.client.ClientThread;
import net.server.ServerThread;

/**
 *
 * @author amind_000
 */
public class ServerCreationPanel extends javax.swing.JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 3965435215937886498L;
	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton createServerButton;

    private javax.swing.JLabel ipLabel;

    private javax.swing.JLabel jLabel1;

    private javax.swing.JLabel jLabel3;

    private javax.swing.JLabel jLabel4;


    private javax.swing.JLabel jLabel7;
    private ApplicationManager listener;
    private javax.swing.JLabel maxPlayersLabel;
    private javax.swing.JSlider maxPlayersSlider;
    private javax.swing.JButton moreButton;
    private javax.swing.JToggleButton playAsClientToggle;
    private javax.swing.JTextField serverNameField;
    private javax.swing.JPasswordField serverPasswordField;
    // End of variables declaration//GEN-END:variables
    /**
     * Creates new form ServerCreation
     */ 
    public ServerCreationPanel(ApplicationManager listener) {
        initComponents();
        this.listener=listener;
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        listener.progressTo(AppState.HOME);
    }//GEN-LAST:event_backButtonActionPerformed
    private void createServerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createServerButtonActionPerformed
    	String name=serverNameField.getText();
    	int players=maxPlayersSlider.getValue();
		ServerThread server = GameHooks.createServer(name, Config.PORT, players);
		String address=server.getInfo().getAddress();
		if(playAsClientToggle.isSelected()){
			GameHooks.createClient(address,Config.PORT,listener.getUser().getName(),listener);
		}
    }//GEN-LAST:event_createServerButtonActionPerformed
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        playAsClientToggle = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        maxPlayersSlider = new javax.swing.JSlider();
        serverNameField = new javax.swing.JTextField();
        serverPasswordField = new javax.swing.JPasswordField();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ipLabel = new javax.swing.JLabel();
        maxPlayersLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        moreButton = new javax.swing.JButton();
        createServerButton = new javax.swing.JButton();

        playAsClientToggle.setText("Play as Client");
        playAsClientToggle.setSelected(true);
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Create a Game");

        serverPasswordField.setToolTipText("Leave blank for no password");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Server Password");

        jLabel4.setText("Server Name");

        ipLabel.setText("10.208.1.11");

        maxPlayersLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        maxPlayersLabel.setText("16");
        
        maxPlayersSlider.setMaximum(net.Config.MAX_CLIENTS);
        maxPlayersSlider.addChangeListener(new ChangeListener(){

			@Override
			public void stateChanged(ChangeEvent e) {
				maxPlayersLabel.setText(maxPlayersSlider.getValue()+"");
			}
        	
        });
        jLabel7.setText("Max Players");

        moreButton.setText("More Options...");
        moreButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreButtonActionPerformed(evt);
            }
        });

        createServerButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        createServerButton.setText("Create");
        createServerButton.addActionListener(new java.awt.event.ActionListener() {
            @Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
                createServerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipLabel)
                    .addComponent(serverNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(serverPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(97, 97, 97)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(maxPlayersSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(maxPlayersLabel))
                                .addComponent(backButton)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(playAsClientToggle, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(moreButton))
                                .addComponent(createServerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jLabel1))))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ipLabel)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serverPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxPlayersSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxPlayersLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playAsClientToggle)
                    .addComponent(moreButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createServerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void moreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moreButtonActionPerformed
}
