// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/SimpleExchange.proto

package net.proto;

public final class SimpleExchangeProto {
  private SimpleExchangeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(net.proto.SimpleExchangeProto.SimpleExchange.simpleExchange);
  }
  public interface SimpleExchangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SimpleExchange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
     */
    boolean hasRequest();
    /**
     * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
     */
    net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest getRequest();
    /**
     * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
     */
    net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
     */
    boolean hasResponse();
    /**
     * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
     */
    net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse getResponse();
    /**
     * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
     */
    net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponseOrBuilder getResponseOrBuilder();
  }
  /**
   * Protobuf type {@code SimpleExchange}
   */
  public  static final class SimpleExchange extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SimpleExchange)
      SimpleExchangeOrBuilder {
    // Use SimpleExchange.newBuilder() to construct.
    private SimpleExchange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SimpleExchange() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimpleExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = response_.toBuilder();
              }
              response_ = input.readMessage(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(response_);
                response_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.proto.SimpleExchangeProto.SimpleExchange.class, net.proto.SimpleExchangeProto.SimpleExchange.Builder.class);
    }

    public interface SimpleExchangeRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SimpleExchange.SimpleExchangeRequest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .SimpleExchange.SimpleExchangeRequest.RequestType request_type = 1;</code>
       */
      boolean hasRequestType();
      /**
       * <code>required .SimpleExchange.SimpleExchangeRequest.RequestType request_type = 1;</code>
       */
      net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType getRequestType();

      /**
       * <code>optional string request_note = 2;</code>
       */
      boolean hasRequestNote();
      /**
       * <code>optional string request_note = 2;</code>
       */
      java.lang.String getRequestNote();
      /**
       * <code>optional string request_note = 2;</code>
       */
      com.google.protobuf.ByteString
          getRequestNoteBytes();
    }
    /**
     * Protobuf type {@code SimpleExchange.SimpleExchangeRequest}
     */
    public  static final class SimpleExchangeRequest extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:SimpleExchange.SimpleExchangeRequest)
        SimpleExchangeRequestOrBuilder {
      // Use SimpleExchangeRequest.newBuilder() to construct.
      private SimpleExchangeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private SimpleExchangeRequest() {
        requestType_ = 0;
        requestNote_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private SimpleExchangeRequest(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType value = net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  requestType_ = rawValue;
                }
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                requestNote_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.class, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.Builder.class);
      }

      /**
       * Protobuf enum {@code SimpleExchange.SimpleExchangeRequest.RequestType}
       */
      public enum RequestType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>PROBE = 0;</code>
         */
        PROBE(0, 0),
        /**
         * <code>CLUSTER_MEMBERSHIP_REQUEST = 1;</code>
         */
        CLUSTER_MEMBERSHIP_REQUEST(1, 1),
        /**
         * <code>SERVER_NAME = 2;</code>
         */
        SERVER_NAME(2, 2),
        /**
         * <code>SERVER_INFO = 3;</code>
         */
        SERVER_INFO(3, 3),
        /**
         * <code>CLIENT_PING = 4;</code>
         */
        CLIENT_PING(4, 4),
        ;

        /**
         * <code>PROBE = 0;</code>
         */
        public static final int PROBE_VALUE = 0;
        /**
         * <code>CLUSTER_MEMBERSHIP_REQUEST = 1;</code>
         */
        public static final int CLUSTER_MEMBERSHIP_REQUEST_VALUE = 1;
        /**
         * <code>SERVER_NAME = 2;</code>
         */
        public static final int SERVER_NAME_VALUE = 2;
        /**
         * <code>SERVER_INFO = 3;</code>
         */
        public static final int SERVER_INFO_VALUE = 3;
        /**
         * <code>CLIENT_PING = 4;</code>
         */
        public static final int CLIENT_PING_VALUE = 4;


        public final int getNumber() {
          return value;
        }

        public static RequestType valueOf(int value) {
          switch (value) {
            case 0: return PROBE;
            case 1: return CLUSTER_MEMBERSHIP_REQUEST;
            case 2: return SERVER_NAME;
            case 3: return SERVER_INFO;
            case 4: return CLIENT_PING;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<RequestType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            RequestType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<RequestType>() {
                public RequestType findValueByNumber(int number) {
                  return RequestType.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.getDescriptor().getEnumTypes().get(0);
        }

        private static final RequestType[] VALUES = values();

        public static RequestType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private RequestType(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:SimpleExchange.SimpleExchangeRequest.RequestType)
      }

      private int bitField0_;
      public static final int REQUEST_TYPE_FIELD_NUMBER = 1;
      private int requestType_;
      /**
       * <code>required .SimpleExchange.SimpleExchangeRequest.RequestType request_type = 1;</code>
       */
      public boolean hasRequestType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .SimpleExchange.SimpleExchangeRequest.RequestType request_type = 1;</code>
       */
      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType getRequestType() {
        net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType result = net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType.valueOf(requestType_);
        return result == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType.PROBE : result;
      }

      public static final int REQUEST_NOTE_FIELD_NUMBER = 2;
      private volatile java.lang.Object requestNote_;
      /**
       * <code>optional string request_note = 2;</code>
       */
      public boolean hasRequestNote() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string request_note = 2;</code>
       */
      public java.lang.String getRequestNote() {
        java.lang.Object ref = requestNote_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestNote_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string request_note = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRequestNoteBytes() {
        java.lang.Object ref = requestNote_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestNote_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasRequestType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, requestType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 2, requestNote_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, requestType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(2, requestNote_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code SimpleExchange.SimpleExchangeRequest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:SimpleExchange.SimpleExchangeRequest)
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeRequest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.class, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.Builder.class);
        }

        // Construct using net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          requestType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          requestNote_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeRequest_descriptor;
        }

        public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest getDefaultInstanceForType() {
          return net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.getDefaultInstance();
        }

        public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest build() {
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest buildPartial() {
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest result = new net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.requestType_ = requestType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.requestNote_ = requestNote_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest) {
            return mergeFrom((net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest other) {
          if (other == net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.getDefaultInstance()) return this;
          if (other.hasRequestType()) {
            setRequestType(other.getRequestType());
          }
          if (other.hasRequestNote()) {
            bitField0_ |= 0x00000002;
            requestNote_ = other.requestNote_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasRequestType()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int requestType_ = 0;
        /**
         * <code>required .SimpleExchange.SimpleExchangeRequest.RequestType request_type = 1;</code>
         */
        public boolean hasRequestType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .SimpleExchange.SimpleExchangeRequest.RequestType request_type = 1;</code>
         */
        public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType getRequestType() {
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType result = net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType.valueOf(requestType_);
          return result == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType.PROBE : result;
        }
        /**
         * <code>required .SimpleExchange.SimpleExchangeRequest.RequestType request_type = 1;</code>
         */
        public Builder setRequestType(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.RequestType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          requestType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required .SimpleExchange.SimpleExchangeRequest.RequestType request_type = 1;</code>
         */
        public Builder clearRequestType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          requestType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object requestNote_ = "";
        /**
         * <code>optional string request_note = 2;</code>
         */
        public boolean hasRequestNote() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public java.lang.String getRequestNote() {
          java.lang.Object ref = requestNote_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              requestNote_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public com.google.protobuf.ByteString
            getRequestNoteBytes() {
          java.lang.Object ref = requestNote_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            requestNote_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public Builder setRequestNote(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          requestNote_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public Builder clearRequestNote() {
          bitField0_ = (bitField0_ & ~0x00000002);
          requestNote_ = getDefaultInstance().getRequestNote();
          onChanged();
          return this;
        }
        /**
         * <code>optional string request_note = 2;</code>
         */
        public Builder setRequestNoteBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          requestNote_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:SimpleExchange.SimpleExchangeRequest)
      }

      // @@protoc_insertion_point(class_scope:SimpleExchange.SimpleExchangeRequest)
      private static final net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest();
      }

      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<SimpleExchangeRequest>
          PARSER = new com.google.protobuf.AbstractParser<SimpleExchangeRequest>() {
        public SimpleExchangeRequest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new SimpleExchangeRequest(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<SimpleExchangeRequest> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<SimpleExchangeRequest> getParserForType() {
        return PARSER;
      }

      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface SimpleExchangeResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SimpleExchange.SimpleExchangeResponse)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required .SimpleExchange.SimpleExchangeResponse.ResponseType response_type = 1;</code>
       */
      boolean hasResponseType();
      /**
       * <code>required .SimpleExchange.SimpleExchangeResponse.ResponseType response_type = 1;</code>
       */
      net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType getResponseType();

      /**
       * <code>optional string response_note = 2;</code>
       */
      boolean hasResponseNote();
      /**
       * <code>optional string response_note = 2;</code>
       */
      java.lang.String getResponseNote();
      /**
       * <code>optional string response_note = 2;</code>
       */
      com.google.protobuf.ByteString
          getResponseNoteBytes();
    }
    /**
     * Protobuf type {@code SimpleExchange.SimpleExchangeResponse}
     */
    public  static final class SimpleExchangeResponse extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:SimpleExchange.SimpleExchangeResponse)
        SimpleExchangeResponseOrBuilder {
      // Use SimpleExchangeResponse.newBuilder() to construct.
      private SimpleExchangeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private SimpleExchangeResponse() {
        responseType_ = 0;
        responseNote_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private SimpleExchangeResponse(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType value = net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  responseType_ = rawValue;
                }
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                responseNote_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.class, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.Builder.class);
      }

      /**
       * Protobuf enum {@code SimpleExchange.SimpleExchangeResponse.ResponseType}
       */
      public enum ResponseType
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>PROBE = 0;</code>
         */
        PROBE(0, 0),
        /**
         * <code>CLUSTER_MEMBERSHIP_ACCEPT = 1;</code>
         */
        CLUSTER_MEMBERSHIP_ACCEPT(1, 1),
        /**
         * <code>CLUSTER_MEMBERSHIP_DENIED = 2;</code>
         */
        CLUSTER_MEMBERSHIP_DENIED(2, 2),
        /**
         * <code>SERVER_NAME = 3;</code>
         */
        SERVER_NAME(3, 3),
        /**
         * <code>SERVER_INFO = 4;</code>
         */
        SERVER_INFO(4, 4),
        /**
         * <code>CLIENT_PING = 5;</code>
         */
        CLIENT_PING(5, 5),
        ;

        /**
         * <code>PROBE = 0;</code>
         */
        public static final int PROBE_VALUE = 0;
        /**
         * <code>CLUSTER_MEMBERSHIP_ACCEPT = 1;</code>
         */
        public static final int CLUSTER_MEMBERSHIP_ACCEPT_VALUE = 1;
        /**
         * <code>CLUSTER_MEMBERSHIP_DENIED = 2;</code>
         */
        public static final int CLUSTER_MEMBERSHIP_DENIED_VALUE = 2;
        /**
         * <code>SERVER_NAME = 3;</code>
         */
        public static final int SERVER_NAME_VALUE = 3;
        /**
         * <code>SERVER_INFO = 4;</code>
         */
        public static final int SERVER_INFO_VALUE = 4;
        /**
         * <code>CLIENT_PING = 5;</code>
         */
        public static final int CLIENT_PING_VALUE = 5;


        public final int getNumber() {
          return value;
        }

        public static ResponseType valueOf(int value) {
          switch (value) {
            case 0: return PROBE;
            case 1: return CLUSTER_MEMBERSHIP_ACCEPT;
            case 2: return CLUSTER_MEMBERSHIP_DENIED;
            case 3: return SERVER_NAME;
            case 4: return SERVER_INFO;
            case 5: return CLIENT_PING;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<ResponseType>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static final com.google.protobuf.Internal.EnumLiteMap<
            ResponseType> internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<ResponseType>() {
                public ResponseType findValueByNumber(int number) {
                  return ResponseType.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.getDescriptor().getEnumTypes().get(0);
        }

        private static final ResponseType[] VALUES = values();

        public static ResponseType valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private ResponseType(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:SimpleExchange.SimpleExchangeResponse.ResponseType)
      }

      private int bitField0_;
      public static final int RESPONSE_TYPE_FIELD_NUMBER = 1;
      private int responseType_;
      /**
       * <code>required .SimpleExchange.SimpleExchangeResponse.ResponseType response_type = 1;</code>
       */
      public boolean hasResponseType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .SimpleExchange.SimpleExchangeResponse.ResponseType response_type = 1;</code>
       */
      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType getResponseType() {
        net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType result = net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType.valueOf(responseType_);
        return result == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType.PROBE : result;
      }

      public static final int RESPONSE_NOTE_FIELD_NUMBER = 2;
      private volatile java.lang.Object responseNote_;
      /**
       * <code>optional string response_note = 2;</code>
       */
      public boolean hasResponseNote() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string response_note = 2;</code>
       */
      public java.lang.String getResponseNote() {
        java.lang.Object ref = responseNote_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            responseNote_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string response_note = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseNoteBytes() {
        java.lang.Object ref = responseNote_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseNote_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasResponseType()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, responseType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          com.google.protobuf.GeneratedMessage.writeString(output, 2, responseNote_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, responseType_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.GeneratedMessage.computeStringSize(2, responseNote_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code SimpleExchange.SimpleExchangeResponse}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:SimpleExchange.SimpleExchangeResponse)
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeResponse_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.class, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.Builder.class);
        }

        // Construct using net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          responseType_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          responseNote_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_SimpleExchangeResponse_descriptor;
        }

        public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse getDefaultInstanceForType() {
          return net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.getDefaultInstance();
        }

        public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse build() {
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse buildPartial() {
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse result = new net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.responseType_ = responseType_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.responseNote_ = responseNote_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse) {
            return mergeFrom((net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse other) {
          if (other == net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.getDefaultInstance()) return this;
          if (other.hasResponseType()) {
            setResponseType(other.getResponseType());
          }
          if (other.hasResponseNote()) {
            bitField0_ |= 0x00000002;
            responseNote_ = other.responseNote_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          if (!hasResponseType()) {
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int responseType_ = 0;
        /**
         * <code>required .SimpleExchange.SimpleExchangeResponse.ResponseType response_type = 1;</code>
         */
        public boolean hasResponseType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required .SimpleExchange.SimpleExchangeResponse.ResponseType response_type = 1;</code>
         */
        public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType getResponseType() {
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType result = net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType.valueOf(responseType_);
          return result == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType.PROBE : result;
        }
        /**
         * <code>required .SimpleExchange.SimpleExchangeResponse.ResponseType response_type = 1;</code>
         */
        public Builder setResponseType(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.ResponseType value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          responseType_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         * <code>required .SimpleExchange.SimpleExchangeResponse.ResponseType response_type = 1;</code>
         */
        public Builder clearResponseType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          responseType_ = 0;
          onChanged();
          return this;
        }

        private java.lang.Object responseNote_ = "";
        /**
         * <code>optional string response_note = 2;</code>
         */
        public boolean hasResponseNote() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public java.lang.String getResponseNote() {
          java.lang.Object ref = responseNote_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              responseNote_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public com.google.protobuf.ByteString
            getResponseNoteBytes() {
          java.lang.Object ref = responseNote_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            responseNote_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public Builder setResponseNote(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          responseNote_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public Builder clearResponseNote() {
          bitField0_ = (bitField0_ & ~0x00000002);
          responseNote_ = getDefaultInstance().getResponseNote();
          onChanged();
          return this;
        }
        /**
         * <code>optional string response_note = 2;</code>
         */
        public Builder setResponseNoteBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          responseNote_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:SimpleExchange.SimpleExchangeResponse)
      }

      // @@protoc_insertion_point(class_scope:SimpleExchange.SimpleExchangeResponse)
      private static final net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse();
      }

      public static net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<SimpleExchangeResponse>
          PARSER = new com.google.protobuf.AbstractParser<SimpleExchangeResponse>() {
        public SimpleExchangeResponse parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new SimpleExchangeResponse(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<SimpleExchangeResponse> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<SimpleExchangeResponse> getParserForType() {
        return PARSER;
      }

      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest request_;
    /**
     * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
     */
    public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest getRequest() {
      return request_ == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.getDefaultInstance() : request_;
    }
    /**
     * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
     */
    public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequestOrBuilder getRequestOrBuilder() {
      return request_ == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.getDefaultInstance() : request_;
    }

    public static final int RESPONSE_FIELD_NUMBER = 2;
    private net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse response_;
    /**
     * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
     */
    public boolean hasResponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
     */
    public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse getResponse() {
      return response_ == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.getDefaultInstance() : response_;
    }
    /**
     * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
     */
    public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponseOrBuilder getResponseOrBuilder() {
      return response_ == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.getDefaultInstance() : response_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasResponse()) {
        if (!getResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getResponse());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static net.proto.SimpleExchangeProto.SimpleExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.proto.SimpleExchangeProto.SimpleExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.proto.SimpleExchangeProto.SimpleExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.proto.SimpleExchangeProto.SimpleExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.proto.SimpleExchangeProto.SimpleExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.proto.SimpleExchangeProto.SimpleExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static net.proto.SimpleExchangeProto.SimpleExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static net.proto.SimpleExchangeProto.SimpleExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static net.proto.SimpleExchangeProto.SimpleExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static net.proto.SimpleExchangeProto.SimpleExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.proto.SimpleExchangeProto.SimpleExchange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SimpleExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SimpleExchange)
        net.proto.SimpleExchangeProto.SimpleExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.proto.SimpleExchangeProto.SimpleExchange.class, net.proto.SimpleExchangeProto.SimpleExchange.Builder.class);
      }

      // Construct using net.proto.SimpleExchangeProto.SimpleExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getResponseFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = null;
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (responseBuilder_ == null) {
          response_ = null;
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.proto.SimpleExchangeProto.internal_static_SimpleExchange_descriptor;
      }

      public net.proto.SimpleExchangeProto.SimpleExchange getDefaultInstanceForType() {
        return net.proto.SimpleExchangeProto.SimpleExchange.getDefaultInstance();
      }

      public net.proto.SimpleExchangeProto.SimpleExchange build() {
        net.proto.SimpleExchangeProto.SimpleExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.proto.SimpleExchangeProto.SimpleExchange buildPartial() {
        net.proto.SimpleExchangeProto.SimpleExchange result = new net.proto.SimpleExchangeProto.SimpleExchange(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (responseBuilder_ == null) {
          result.response_ = response_;
        } else {
          result.response_ = responseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.proto.SimpleExchangeProto.SimpleExchange) {
          return mergeFrom((net.proto.SimpleExchangeProto.SimpleExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.proto.SimpleExchangeProto.SimpleExchange other) {
        if (other == net.proto.SimpleExchangeProto.SimpleExchange.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasResponse()) {
          mergeResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            return false;
          }
        }
        if (hasResponse()) {
          if (!getResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.proto.SimpleExchangeProto.SimpleExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.proto.SimpleExchangeProto.SimpleExchange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest request_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.Builder, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
       */
      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_ == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.getDefaultInstance() : request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
       */
      public Builder setRequest(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
       */
      public Builder setRequest(
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
       */
      public Builder mergeRequest(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              request_ != null &&
              request_ != net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.getDefaultInstance()) {
            request_ =
              net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = null;
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
       */
      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
       */
      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_ == null ?
              net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.getDefaultInstance() : request_;
        }
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeRequest request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.Builder, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequest.Builder, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse response_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.Builder, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponseOrBuilder> responseBuilder_;
      /**
       * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
       */
      public boolean hasResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
       */
      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse getResponse() {
        if (responseBuilder_ == null) {
          return response_ == null ? net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.getDefaultInstance() : response_;
        } else {
          return responseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
       */
      public Builder setResponse(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse value) {
        if (responseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          response_ = value;
          onChanged();
        } else {
          responseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
       */
      public Builder setResponse(
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.Builder builderForValue) {
        if (responseBuilder_ == null) {
          response_ = builderForValue.build();
          onChanged();
        } else {
          responseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
       */
      public Builder mergeResponse(net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse value) {
        if (responseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              response_ != null &&
              response_ != net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.getDefaultInstance()) {
            response_ =
              net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.newBuilder(response_).mergeFrom(value).buildPartial();
          } else {
            response_ = value;
          }
          onChanged();
        } else {
          responseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
       */
      public Builder clearResponse() {
        if (responseBuilder_ == null) {
          response_ = null;
          onChanged();
        } else {
          responseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
       */
      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.Builder getResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
       */
      public net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponseOrBuilder getResponseOrBuilder() {
        if (responseBuilder_ != null) {
          return responseBuilder_.getMessageOrBuilder();
        } else {
          return response_ == null ?
              net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.getDefaultInstance() : response_;
        }
      }
      /**
       * <code>optional .SimpleExchange.SimpleExchangeResponse response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.Builder, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponseOrBuilder> 
          getResponseFieldBuilder() {
        if (responseBuilder_ == null) {
          responseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponse.Builder, net.proto.SimpleExchangeProto.SimpleExchange.SimpleExchangeResponseOrBuilder>(
                  getResponse(),
                  getParentForChildren(),
                  isClean());
          response_ = null;
        }
        return responseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SimpleExchange)
    }

    // @@protoc_insertion_point(class_scope:SimpleExchange)
    private static final net.proto.SimpleExchangeProto.SimpleExchange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.proto.SimpleExchangeProto.SimpleExchange();
    }

    public static net.proto.SimpleExchangeProto.SimpleExchange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SimpleExchange>
        PARSER = new com.google.protobuf.AbstractParser<SimpleExchange>() {
      public SimpleExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new SimpleExchange(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<SimpleExchange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimpleExchange> getParserForType() {
      return PARSER;
    }

    public net.proto.SimpleExchangeProto.SimpleExchange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int SIMPLE_EXCHANGE_FIELD_NUMBER = 4;
    /**
     * <code>extend .exchange { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        net.proto.ExchangeProto.exchange,
        net.proto.SimpleExchangeProto.SimpleExchange> simpleExchange = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          net.proto.SimpleExchangeProto.SimpleExchange.getDefaultInstance(),
          0,
          net.proto.SimpleExchangeProto.SimpleExchange.class,
          net.proto.SimpleExchangeProto.SimpleExchange.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleExchange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SimpleExchange_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleExchange_SimpleExchangeRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SimpleExchange_SimpleExchangeRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_SimpleExchange_SimpleExchangeResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SimpleExchange_SimpleExchangeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032proto/SimpleExchange.proto\032\024proto/Exch" +
      "ange.proto\"\250\005\n\016SimpleExchange\0226\n\007request" +
      "\030\001 \001(\0132%.SimpleExchange.SimpleExchangeRe" +
      "quest\0228\n\010response\030\002 \001(\0132&.SimpleExchange" +
      ".SimpleExchangeResponse\032\343\001\n\025SimpleExchan" +
      "geRequest\022G\n\014request_type\030\001 \002(\01621.Simple" +
      "Exchange.SimpleExchangeRequest.RequestTy" +
      "pe\022\024\n\014request_note\030\002 \001(\t\"k\n\013RequestType\022" +
      "\t\n\005PROBE\020\000\022\036\n\032CLUSTER_MEMBERSHIP_REQUEST" +
      "\020\001\022\017\n\013SERVER_NAME\020\002\022\017\n\013SERVER_INFO\020\003\022\017\n\013",
      "CLIENT_PING\020\004\032\210\002\n\026SimpleExchangeResponse" +
      "\022J\n\rresponse_type\030\001 \002(\01623.SimpleExchange" +
      ".SimpleExchangeResponse.ResponseType\022\025\n\r" +
      "response_note\030\002 \001(\t\"\212\001\n\014ResponseType\022\t\n\005" +
      "PROBE\020\000\022\035\n\031CLUSTER_MEMBERSHIP_ACCEPT\020\001\022\035" +
      "\n\031CLUSTER_MEMBERSHIP_DENIED\020\002\022\017\n\013SERVER_" +
      "NAME\020\003\022\017\n\013SERVER_INFO\020\004\022\017\n\013CLIENT_PING\020\005" +
      "23\n\017simple_exchange\022\t.exchange\030\004 \001(\0132\017.S" +
      "impleExchangeB \n\tnet.protoB\023SimpleExchan" +
      "geProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.proto.ExchangeProto.getDescriptor(),
        }, assigner);
    internal_static_SimpleExchange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SimpleExchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SimpleExchange_descriptor,
        new java.lang.String[] { "Request", "Response", });
    internal_static_SimpleExchange_SimpleExchangeRequest_descriptor =
      internal_static_SimpleExchange_descriptor.getNestedTypes().get(0);
    internal_static_SimpleExchange_SimpleExchangeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SimpleExchange_SimpleExchangeRequest_descriptor,
        new java.lang.String[] { "RequestType", "RequestNote", });
    internal_static_SimpleExchange_SimpleExchangeResponse_descriptor =
      internal_static_SimpleExchange_descriptor.getNestedTypes().get(1);
    internal_static_SimpleExchange_SimpleExchangeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SimpleExchange_SimpleExchangeResponse_descriptor,
        new java.lang.String[] { "ResponseType", "ResponseNote", });
    net.proto.ExchangeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
