/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panel.serverselect;

import java.awt.FlowLayout;
import java.util.Timer;

import javax.swing.JPanel;

import multiplayergamelauncher.ProgressListener;

/**
 *
 * @author amind_000
 */
public class ServerSelectPanel extends javax.swing.JPanel {
	FlowLayout layout;
	private JPanel selectSubPanel;
	private JPanel loadingSubPanel;
	private ProgressListener listener;
    /**
     * Creates new form ServerSelectPanel
     */
    public ServerSelectPanel(ProgressListener listener) {
    	loadingSubPanel=new LoadingServersSubPanel(this);
    	selectSubPanel=new ServerSelectSubPanel(this);
    	setPreferredSize(selectSubPanel.getPreferredSize());
    	setMinimumSize(selectSubPanel.getPreferredSize());
        initComponents();
    }
    public void updateServerList(){
    	this.add(loadingSubPanel);
    	new java.util.Timer().schedule( 
    	        new java.util.TimerTask() {
    	            @Override
    	            public void run() {
    	            	removeAll();
    	            	add(selectSubPanel);
    	            	repaint();
    	            }
    	        }, 
    	        5000 
    	);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        layout = new FlowLayout();
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
