/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package panel.serverselect;

import java.util.ArrayList;

import multiplayergamelauncher.AppState;
import multiplayergamelauncher.AppUtil;
import net.Config;
import net.client.ClientThread;

/**
 *
 * @author amind_000
 */
public class ServerSelectSubPanel extends javax.swing.JPanel {
	/**
	 * 
	 */
	private static final long serialVersionUID = 4399569016413037617L;
	ServerSelectPanel parent;

	/**
	 * Creates new form ServerSelectSubPanel
	 */
	public ServerSelectSubPanel(ServerSelectPanel parent) {
		initComponents();
		this.parent = parent;
	}

	protected void onEnter() {
		final ArrayList<String> strings = new ArrayList<>();
		strings.addAll(parent.servers.keySet());
		System.out.println(strings);
		jList1.setModel(new javax.swing.AbstractListModel<String>() {

			/**
			 * 
			 */
			private static final long serialVersionUID = 1L;

			public int getSize() {
				return strings.size();
			}

			public String getElementAt(int i) {
				return strings.get(i);
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jList1 = new javax.swing.JList<String>();
		jLabel1 = new javax.swing.JLabel();
		selectServerButton = new javax.swing.JButton();
		backButton = new javax.swing.JButton();
		refreshButton = new javax.swing.JButton();

		jList1.setModel(new javax.swing.AbstractListModel<String>() {
			/**
			 * 
			 */
			private static final long serialVersionUID = 4570288960508034826L;
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

			public int getSize() {
				return strings.length;
			}

			public String getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(jList1);

		jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
		jLabel1.setText("Server Select");

		selectServerButton.setText("Select");
		selectServerButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				selectServerButtonActionPerformed(evt);
			}
		});

		backButton.setText("Back");
		backButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backButtonActionPerformed(evt);
			}
		});

		refreshButton.setText("Refresh");
		refreshButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				refreshButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(105, Short.MAX_VALUE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										layout.createSequentialGroup()
												.addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(refreshButton))
								.addComponent(jScrollPane1)
								.addGroup(layout.createSequentialGroup().addGap(8, 8, 8).addComponent(jLabel1))
								.addComponent(selectServerButton, javax.swing.GroupLayout.DEFAULT_SIZE, 175,
										Short.MAX_VALUE))
						.addGap(110, 110, 110)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap().addComponent(jLabel1).addGap(36, 36, 36)
						.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(selectServerButton)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(backButton).addComponent(refreshButton)).addContainerGap(36, Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void selectServerButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectServerButtonActionPerformed
		String address = parent.servers.get(jList1.getSelectedValue());
		ClientThread client=AppUtil.createClient(address, Config.PORT, parent.listener.getUser().getName(), parent.listener);
	}// GEN-LAST:event_selectServerButtonActionPerformed

	private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_backButtonActionPerformed
		parent.listener.progressTo(AppState.HOME);
	}// GEN-LAST:event_backButtonActionPerformed

	private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_refreshButtonActionPerformed
		parent.updateServerList();
	}// GEN-LAST:event_refreshButtonActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton backButton;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JList<String> jList1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JButton refreshButton;
	private javax.swing.JButton selectServerButton;
	// End of variables declaration//GEN-END:variables
}
