// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/onlineBoxGame/GameExchange.proto

package proto;

public final class GameStateExchangeProto {
  private GameStateExchangeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(proto.GameStateExchangeProto.GameStateExchange.gameUpdate);
  }
  public interface GameStateExchangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GameStateExchange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    java.util.List<proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage> 
        getObjectsList();
    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage getObjects(int index);
    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    int getObjectsCount();
    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    java.util.List<? extends proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder> 
        getObjectsOrBuilderList();
    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder getObjectsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code GameStateExchange}
   */
  public  static final class GameStateExchange extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GameStateExchange)
      GameStateExchangeOrBuilder {
    // Use GameStateExchange.newBuilder() to construct.
    private GameStateExchange(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GameStateExchange() {
      objects_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GameStateExchange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                objects_ = new java.util.ArrayList<proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              objects_.add(input.readMessage(proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          objects_ = java.util.Collections.unmodifiableList(objects_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.GameStateExchangeProto.internal_static_GameStateExchange_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.GameStateExchangeProto.internal_static_GameStateExchange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.GameStateExchangeProto.GameStateExchange.class, proto.GameStateExchangeProto.GameStateExchange.Builder.class);
    }

    public interface GameObjectMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:GameStateExchange.GameObjectMessage)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 posX = 1;</code>
       */
      boolean hasPosX();
      /**
       * <code>optional int32 posX = 1;</code>
       */
      int getPosX();

      /**
       * <code>optional int32 posY = 2;</code>
       */
      boolean hasPosY();
      /**
       * <code>optional int32 posY = 2;</code>
       */
      int getPosY();
    }
    /**
     * Protobuf type {@code GameStateExchange.GameObjectMessage}
     */
    public  static final class GameObjectMessage extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:GameStateExchange.GameObjectMessage)
        GameObjectMessageOrBuilder {
      // Use GameObjectMessage.newBuilder() to construct.
      private GameObjectMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
      }
      private GameObjectMessage() {
        posX_ = 0;
        posY_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private GameObjectMessage(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
        this();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                posX_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                posY_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.GameStateExchangeProto.internal_static_GameStateExchange_GameObjectMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.GameStateExchangeProto.internal_static_GameStateExchange_GameObjectMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.class, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder.class);
      }

      private int bitField0_;
      public static final int POSX_FIELD_NUMBER = 1;
      private int posX_;
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public boolean hasPosX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 posX = 1;</code>
       */
      public int getPosX() {
        return posX_;
      }

      public static final int POSY_FIELD_NUMBER = 2;
      private int posY_;
      /**
       * <code>optional int32 posY = 2;</code>
       */
      public boolean hasPosY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 posY = 2;</code>
       */
      public int getPosY() {
        return posY_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, posX_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, posY_);
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, posX_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, posY_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code GameStateExchange.GameObjectMessage}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:GameStateExchange.GameObjectMessage)
          proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return proto.GameStateExchangeProto.internal_static_GameStateExchange_GameObjectMessage_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return proto.GameStateExchangeProto.internal_static_GameStateExchange_GameObjectMessage_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.class, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder.class);
        }

        // Construct using proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          posX_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          posY_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return proto.GameStateExchangeProto.internal_static_GameStateExchange_GameObjectMessage_descriptor;
        }

        public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage getDefaultInstanceForType() {
          return proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.getDefaultInstance();
        }

        public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage build() {
          proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage buildPartial() {
          proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage result = new proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.posX_ = posX_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.posY_ = posY_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage) {
            return mergeFrom((proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage other) {
          if (other == proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.getDefaultInstance()) return this;
          if (other.hasPosX()) {
            setPosX(other.getPosX());
          }
          if (other.hasPosY()) {
            setPosY(other.getPosY());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int posX_ ;
        /**
         * <code>optional int32 posX = 1;</code>
         */
        public boolean hasPosX() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int32 posX = 1;</code>
         */
        public int getPosX() {
          return posX_;
        }
        /**
         * <code>optional int32 posX = 1;</code>
         */
        public Builder setPosX(int value) {
          bitField0_ |= 0x00000001;
          posX_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 posX = 1;</code>
         */
        public Builder clearPosX() {
          bitField0_ = (bitField0_ & ~0x00000001);
          posX_ = 0;
          onChanged();
          return this;
        }

        private int posY_ ;
        /**
         * <code>optional int32 posY = 2;</code>
         */
        public boolean hasPosY() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 posY = 2;</code>
         */
        public int getPosY() {
          return posY_;
        }
        /**
         * <code>optional int32 posY = 2;</code>
         */
        public Builder setPosY(int value) {
          bitField0_ |= 0x00000002;
          posY_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 posY = 2;</code>
         */
        public Builder clearPosY() {
          bitField0_ = (bitField0_ & ~0x00000002);
          posY_ = 0;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:GameStateExchange.GameObjectMessage)
      }

      // @@protoc_insertion_point(class_scope:GameStateExchange.GameObjectMessage)
      private static final proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage();
      }

      public static proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<GameObjectMessage>
          PARSER = new com.google.protobuf.AbstractParser<GameObjectMessage>() {
        public GameObjectMessage parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          try {
            return new GameObjectMessage(input, extensionRegistry);
          } catch (RuntimeException e) {
            if (e.getCause() instanceof
                com.google.protobuf.InvalidProtocolBufferException) {
              throw (com.google.protobuf.InvalidProtocolBufferException)
                  e.getCause();
            }
            throw e;
          }
        }
      };

      public static com.google.protobuf.Parser<GameObjectMessage> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<GameObjectMessage> getParserForType() {
        return PARSER;
      }

      public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int OBJECTS_FIELD_NUMBER = 1;
    private java.util.List<proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage> objects_;
    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    public java.util.List<proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage> getObjectsList() {
      return objects_;
    }
    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    public java.util.List<? extends proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder> 
        getObjectsOrBuilderList() {
      return objects_;
    }
    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    public int getObjectsCount() {
      return objects_.size();
    }
    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage getObjects(int index) {
      return objects_.get(index);
    }
    /**
     * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
     */
    public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder getObjectsOrBuilder(
        int index) {
      return objects_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < objects_.size(); i++) {
        output.writeMessage(1, objects_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < objects_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, objects_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static proto.GameStateExchangeProto.GameStateExchange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GameStateExchangeProto.GameStateExchange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GameStateExchangeProto.GameStateExchange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.GameStateExchangeProto.GameStateExchange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.GameStateExchangeProto.GameStateExchange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.GameStateExchangeProto.GameStateExchange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.GameStateExchangeProto.GameStateExchange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.GameStateExchangeProto.GameStateExchange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.GameStateExchangeProto.GameStateExchange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.GameStateExchangeProto.GameStateExchange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.GameStateExchangeProto.GameStateExchange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GameStateExchange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GameStateExchange)
        proto.GameStateExchangeProto.GameStateExchangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.GameStateExchangeProto.internal_static_GameStateExchange_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.GameStateExchangeProto.internal_static_GameStateExchange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.GameStateExchangeProto.GameStateExchange.class, proto.GameStateExchangeProto.GameStateExchange.Builder.class);
      }

      // Construct using proto.GameStateExchangeProto.GameStateExchange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getObjectsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (objectsBuilder_ == null) {
          objects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          objectsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.GameStateExchangeProto.internal_static_GameStateExchange_descriptor;
      }

      public proto.GameStateExchangeProto.GameStateExchange getDefaultInstanceForType() {
        return proto.GameStateExchangeProto.GameStateExchange.getDefaultInstance();
      }

      public proto.GameStateExchangeProto.GameStateExchange build() {
        proto.GameStateExchangeProto.GameStateExchange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.GameStateExchangeProto.GameStateExchange buildPartial() {
        proto.GameStateExchangeProto.GameStateExchange result = new proto.GameStateExchangeProto.GameStateExchange(this);
        int from_bitField0_ = bitField0_;
        if (objectsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            objects_ = java.util.Collections.unmodifiableList(objects_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.objects_ = objects_;
        } else {
          result.objects_ = objectsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.GameStateExchangeProto.GameStateExchange) {
          return mergeFrom((proto.GameStateExchangeProto.GameStateExchange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.GameStateExchangeProto.GameStateExchange other) {
        if (other == proto.GameStateExchangeProto.GameStateExchange.getDefaultInstance()) return this;
        if (objectsBuilder_ == null) {
          if (!other.objects_.isEmpty()) {
            if (objects_.isEmpty()) {
              objects_ = other.objects_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureObjectsIsMutable();
              objects_.addAll(other.objects_);
            }
            onChanged();
          }
        } else {
          if (!other.objects_.isEmpty()) {
            if (objectsBuilder_.isEmpty()) {
              objectsBuilder_.dispose();
              objectsBuilder_ = null;
              objects_ = other.objects_;
              bitField0_ = (bitField0_ & ~0x00000001);
              objectsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getObjectsFieldBuilder() : null;
            } else {
              objectsBuilder_.addAllMessages(other.objects_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.GameStateExchangeProto.GameStateExchange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.GameStateExchangeProto.GameStateExchange) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage> objects_ =
        java.util.Collections.emptyList();
      private void ensureObjectsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          objects_ = new java.util.ArrayList<proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage>(objects_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder> objectsBuilder_;

      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public java.util.List<proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage> getObjectsList() {
        if (objectsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(objects_);
        } else {
          return objectsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public int getObjectsCount() {
        if (objectsBuilder_ == null) {
          return objects_.size();
        } else {
          return objectsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage getObjects(int index) {
        if (objectsBuilder_ == null) {
          return objects_.get(index);
        } else {
          return objectsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public Builder setObjects(
          int index, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage value) {
        if (objectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectsIsMutable();
          objects_.set(index, value);
          onChanged();
        } else {
          objectsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public Builder setObjects(
          int index, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder builderForValue) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.set(index, builderForValue.build());
          onChanged();
        } else {
          objectsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public Builder addObjects(proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage value) {
        if (objectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectsIsMutable();
          objects_.add(value);
          onChanged();
        } else {
          objectsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public Builder addObjects(
          int index, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage value) {
        if (objectsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureObjectsIsMutable();
          objects_.add(index, value);
          onChanged();
        } else {
          objectsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public Builder addObjects(
          proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder builderForValue) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.add(builderForValue.build());
          onChanged();
        } else {
          objectsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public Builder addObjects(
          int index, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder builderForValue) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.add(index, builderForValue.build());
          onChanged();
        } else {
          objectsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public Builder addAllObjects(
          java.lang.Iterable<? extends proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage> values) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, objects_);
          onChanged();
        } else {
          objectsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public Builder clearObjects() {
        if (objectsBuilder_ == null) {
          objects_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          objectsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public Builder removeObjects(int index) {
        if (objectsBuilder_ == null) {
          ensureObjectsIsMutable();
          objects_.remove(index);
          onChanged();
        } else {
          objectsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder getObjectsBuilder(
          int index) {
        return getObjectsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder getObjectsOrBuilder(
          int index) {
        if (objectsBuilder_ == null) {
          return objects_.get(index);  } else {
          return objectsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public java.util.List<? extends proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder> 
           getObjectsOrBuilderList() {
        if (objectsBuilder_ != null) {
          return objectsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(objects_);
        }
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder addObjectsBuilder() {
        return getObjectsFieldBuilder().addBuilder(
            proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder addObjectsBuilder(
          int index) {
        return getObjectsFieldBuilder().addBuilder(
            index, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .GameStateExchange.GameObjectMessage objects = 1;</code>
       */
      public java.util.List<proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder> 
           getObjectsBuilderList() {
        return getObjectsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder> 
          getObjectsFieldBuilder() {
        if (objectsBuilder_ == null) {
          objectsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessage.Builder, proto.GameStateExchangeProto.GameStateExchange.GameObjectMessageOrBuilder>(
                  objects_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          objects_ = null;
        }
        return objectsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:GameStateExchange)
    }

    // @@protoc_insertion_point(class_scope:GameStateExchange)
    private static final proto.GameStateExchangeProto.GameStateExchange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.GameStateExchangeProto.GameStateExchange();
    }

    public static proto.GameStateExchangeProto.GameStateExchange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GameStateExchange>
        PARSER = new com.google.protobuf.AbstractParser<GameStateExchange>() {
      public GameStateExchange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GameStateExchange(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GameStateExchange> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GameStateExchange> getParserForType() {
      return PARSER;
    }

    public proto.GameStateExchangeProto.GameStateExchange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

    public static final int GAME_UPDATE_FIELD_NUMBER = 5;
    /**
     * <code>extend .exchange { ... }</code>
     */
    public static final
      com.google.protobuf.GeneratedMessage.GeneratedExtension<
        net.proto.ExchangeProto.exchange,
        proto.GameStateExchangeProto.GameStateExchange> gameUpdate = com.google.protobuf.GeneratedMessage
            .newMessageScopedGeneratedExtension(
          proto.GameStateExchangeProto.GameStateExchange.getDefaultInstance(),
          0,
          proto.GameStateExchangeProto.GameStateExchange.class,
          proto.GameStateExchangeProto.GameStateExchange.getDefaultInstance());
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GameStateExchange_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameStateExchange_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GameStateExchange_GameObjectMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameStateExchange_GameObjectMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n&proto/onlineBoxGame/GameExchange.proto" +
      "\032\024proto/Exchange.proto\"\257\001\n\021GameStateExch" +
      "ange\0225\n\007objects\030\001 \003(\0132$.GameStateExchang" +
      "e.GameObjectMessage\032/\n\021GameObjectMessage" +
      "\022\014\n\004posX\030\001 \001(\005\022\014\n\004posY\030\002 \001(\00522\n\013game_upd" +
      "ate\022\t.exchange\030\005 \001(\0132\022.GameStateExchange" +
      "B\037\n\005protoB\026GameStateExchangeProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.proto.ExchangeProto.getDescriptor(),
        }, assigner);
    internal_static_GameStateExchange_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GameStateExchange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GameStateExchange_descriptor,
        new java.lang.String[] { "Objects", });
    internal_static_GameStateExchange_GameObjectMessage_descriptor =
      internal_static_GameStateExchange_descriptor.getNestedTypes().get(0);
    internal_static_GameStateExchange_GameObjectMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GameStateExchange_GameObjectMessage_descriptor,
        new java.lang.String[] { "PosX", "PosY", });
    net.proto.ExchangeProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
